### ISSUE TITLE
El bad da exepcion de list index out of range

### ISSUE THREAD

**Issue by gevovlockas** [juanps90/pgrado#26]
Cuando inicias la ejecucion,  y antes de los 10 segundos de pasado el comportamiento 0, si pones bad tira el siguiente error a pesar de que el grafo lo muestra bien.

[ERROR] [WallTime: 1459136101.100084] bad callback: <bound method irA.atenderNivel of <__main__.irA object at 0x7f2491de8150>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 688, in _invoke_callback
    cb(msg)
  File "/home/viki/catkin_ws/src/learning_by_imitation/scripts/comportamiento.py", line 331, in atenderNivel
    ultimoNodo=c[len(c)-1] #ultimo nodo del camino previo
IndexError: list index out of range

**Comment by gevovlockas** [comment]
Al parecer este error da solo al intentar eliminar el nodo 0. Otra cosa que paso es que cuando estaba en el nodo 1, y antes de que pasaran los 10 segundos, elimino el nodo 1 cuando creo que debio haber eliminado el nodo 0. Pero no tiro nunca excepcion.
